import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#6cfe9f",
        surface: "#f4fafd",
        "on-primary-fixed": "#00210d",
        secondary: "#346944",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006d38",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbd2",
        "tertiary-fixed-dim": "#ffb4a1",
        "surface-dim": "#d4dbdd",
        "on-tertiary": "#ffffff",
        outline: "#6c7b6d",
        "secondary-fixed-dim": "#9bd4a6",
        "on-error": "#ffffff",
        "surface-container": "#e8eff1",
        "on-surface": "#161d1f",
        "surface-container-low": "#eef5f7",
        tertiary: "#9c432c",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#00210d",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dde4e6",
        "on-primary-container": "#004d25",
        "error-container": "#ffdad6",
        "inverse-surface": "#2b3234",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#3c0800",
        "secondary-container": "#b6f0c1",
        "on-secondary-fixed-variant": "#1b502e",
        "on-tertiary-fixed-variant": "#7d2c17",
        "on-secondary-container": "#3a6f4a",
        "on-tertiary-container": "#762813",
        "outline-variant": "#bbcabb",
        "primary-container": "#28c76f",
        primary: "#006d38",
        "secondary-fixed": "#b6f0c1",
        "on-primary-fixed-variant": "#005229",
        "on-surface-variant": "#3d4a3e",
        "surface-bright": "#f4fafd",
        "on-background": "#161d1f",
        background: "#f4fafd",
        "inverse-primary": "#4be085",
        "surface-container-high": "#e2e9ec",
        "primary-fixed-dim": "#4be085",
        "inverse-on-surface": "#ebf2f4",
        "surface-variant": "#dde4e6",
        "tertiary-container": "#ff9073",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "PingFang SC", "sans-serif"],
        body: ["Inter", "PingFang SC", "sans-serif"],
        label: ["Inter", "PingFang SC", "sans-serif"],
        "plus-jakarta": ["Plus Jakarta Sans", "PingFang SC", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [forms, containerQueries],
};
